CREATE SCHEMA IF NOT EXISTS estrategias;

CREATE TABLE IF NOT EXISTS estrategias.dividendos (
    ticker              VARCHAR(10)     NOT NULL,
    snapshot_date       DATE            NOT NULL,
    companyname         TEXT,
    sector              TEXT,
    market_cap_tier     TEXT,
    quality_score       NUMERIC(6,2),
    value_score         NUMERIC(6,2),
    altman_z_score      NUMERIC(8,4),
    altman_zona         VARCHAR(20),
    piotroski_score     SMALLINT,
    roic_signo          SMALLINT,
    deuda_signo         SMALLINT,
    rsi_14_semanal      NUMERIC(6,2),
    precio_vs_ma200     NUMERIC(8,4),
    sector_alineado     VARCHAR(20),
    dividend_yield      NUMERIC(8,4),
    debt_to_equity      NUMERIC(8,4),
    interest_coverage   NUMERIC(8,4),
    operating_margin    NUMERIC(8,4),
    roic                NUMERIC(8,4),
    net_debt_ebitda     NUMERIC(8,4),
    momentum_3m         NUMERIC(8,4),
    momentum_6m         NUMERIC(8,4),
    ranking             INTEGER,
    PRIMARY KEY (ticker, snapshot_date)
);

CREATE TABLE IF NOT EXISTS estrategias.buy_hold (
    ticker              VARCHAR(10)     NOT NULL,
    snapshot_date       DATE            NOT NULL,
    companyname         TEXT,
    sector              TEXT,
    market_cap_tier     TEXT,
    quality_score       NUMERIC(6,2),
    value_score         NUMERIC(6,2),
    altman_z_score      NUMERIC(8,4),
    altman_zona         VARCHAR(20),
    piotroski_score     SMALLINT,
    roic_signo          SMALLINT,
    deuda_signo         SMALLINT,
    rsi_14_semanal      NUMERIC(6,2),
    precio_vs_ma200     NUMERIC(8,4),
    sector_alineado     VARCHAR(20),
    dividend_yield      NUMERIC(8,4),
    operating_margin    NUMERIC(8,4),
    interest_coverage   NUMERIC(8,4),
    roic                NUMERIC(8,4),
    net_debt_ebitda     NUMERIC(8,4),
    ranking             INTEGER,
    PRIMARY KEY (ticker, snapshot_date)
);

CREATE TABLE IF NOT EXISTS estrategias.cash_flow (
    ticker              VARCHAR(10)     NOT NULL,
    snapshot_date       DATE            NOT NULL,
    companyname         TEXT,
    sector              TEXT,
    market_cap_tier     TEXT,
    quality_score       NUMERIC(6,2),
    value_score         NUMERIC(6,2),
    altman_z_score      NUMERIC(8,4),
    altman_zona         VARCHAR(20),
    piotroski_score     SMALLINT,
    roic_signo          SMALLINT,
    deuda_signo         SMALLINT,
    rsi_14_semanal      NUMERIC(6,2),
    sector_alineado     VARCHAR(20),
    dividend_yield      NUMERIC(8,4),
    instrumento         VARCHAR(30),
    score_conviccion    NUMERIC(6,2),
    flag_timing         VARCHAR(30),
    put_strike          NUMERIC(10,2),
    put_delta           NUMERIC(8,4),
    put_theta           NUMERIC(8,4),
    put_iv              NUMERIC(8,4),
    put_dte             INTEGER,
    nivel_iv            VARCHAR(10),
    sizing              NUMERIC(4,2),
    ranking             INTEGER,
    PRIMARY KEY (ticker, snapshot_date)
);

CREATE TABLE IF NOT EXISTS estrategias.the_wheel (
    ticker              VARCHAR(10)     NOT NULL,
    snapshot_date       DATE            NOT NULL,
    companyname         TEXT,
    sector              TEXT,
    market_cap_tier     TEXT,
    quality_score       NUMERIC(6,2),
    value_score         NUMERIC(6,2),
    altman_z_score      NUMERIC(8,4),
    altman_zona         VARCHAR(20),
    piotroski_score     SMALLINT,
    roic_signo          SMALLINT,
    deuda_signo         SMALLINT,
    rsi_14_semanal      NUMERIC(6,2),
    sector_alineado     VARCHAR(20),
    dividend_yield      NUMERIC(8,4),
    operating_margin    NUMERIC(8,4),
    current_ratio       NUMERIC(8,4),
    nivel_iv            VARCHAR(10),
    put_strike          NUMERIC(10,2),
    put_delta           NUMERIC(8,4),
    put_theta           NUMERIC(8,4),
    put_dte             INTEGER,
    ranking             INTEGER,
    PRIMARY KEY (ticker, snapshot_date)
);

CREATE TABLE IF NOT EXISTS estrategias.crecimiento (
    ticker              VARCHAR(10)     NOT NULL,
    snapshot_date       DATE            NOT NULL,
    companyname         TEXT,
    sector              TEXT,
    market_cap_tier     TEXT,
    quality_score       NUMERIC(6,2),
    value_score         NUMERIC(6,2),
    altman_z_score      NUMERIC(8,4),
    altman_zona         VARCHAR(20),
    piotroski_score     SMALLINT,
    roic_signo          SMALLINT,
    deuda_signo         SMALLINT,
    rsi_14_semanal      NUMERIC(6,2),
    precio_vs_ma200     NUMERIC(8,4),
    momentum_3m         NUMERIC(8,4),
    momentum_6m         NUMERIC(8,4),
    momentum_12m        NUMERIC(8,4),
    sector_alineado     VARCHAR(20),
    dividend_yield      NUMERIC(8,4),
    operating_margin    NUMERIC(8,4),
    roic                NUMERIC(8,4),
    ranking             INTEGER,
    PRIMARY KEY (ticker, snapshot_date)
);